bat_cmd="bat --color=always --theme=OneHalfDark"
bindkey -e
alias bat="$bat_cmd"
export PAGER="$bat_cmd"
export BAT_PAGER="less -rF"
export TERM=xterm-256color
alias la="ls -a"
alias vim="nvim"
alias vi="nvim"
alias python="python3"
alias pip="pip3"
alias ack="ack --ignore-dir=build"
alias pjf="pbpaste | jq | pbcopy"
alias scripts="cat package.json | jq .scripts"
alias pkg="cat package.json | jq"
